trigger: none

pool:
  name: Sunil_pool

variables:
- group: TFSecrets

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.9.5'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: 'sunil-app'
    backendAzureRmResourceGroupName: 'Sunil-vault'
    backendAzureRmStorageAccountName: 'sunildev'
    backendAzureRmContainerName: 'file'
    backendAzureRmKey: 'terraform.tfstate'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: 'sunil-app'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    args: '-auto-approve'
    backendServiceArm: 'sunil-app'
