trigger: none

pool:
  name: Sunil_pool

variables:
- group: TFSecrets

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.9.5'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module-usage' 
    backendServiceArm: 'sunil-app' 
    backendAzureRmResourceGroupName: 'Sunil-vault'
    backendAzureRmStorageAccountName: 'sunildev'  
    backendAzureRmContainerName: 'file'  
    backendAzureRmKey: 'terraform.tfstate' 

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module-usage'
    environmentServiceNameAzureRM: 'sunil-app' 
  env:
    public_key: $(PUBLIC_KEY)

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module-usage'
    args: '-auto-approve'
    environmentServiceNameAzureRM: 'sunil-app'  
